### ISSUE TITLE
Content Inventory - Upcoming Programs

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#10]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/upcomingPRO.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by starbuck28** [comment]
# Upcoming Events
A major page linked to from main menu/home page

Content consists of:

**Main Header** (text only)

**JACO logo** 

**Subheader**
	
- Instructions on program registration including
- 	Link to online payment @ Eventzilla (same window)
- 	Phone number
- 	How to mail payment

**Subheader**-Link to Second Saturdays page
(unclear from page what this is)

**Events List** consisting of:
- H1 Header (Title of Event)
- Subheader with presenter info
-Image (if available)
- Date and time
- Location (link to Google Map)
- Description of event
- Level of knowledge needed
- Section about author
- Link to flyer (pdf in same window)
- Link to online registration

**Upcoming Events Section** (condensed version of events)
- Calendar icon
- Title
- Date/Time
- Location
- Link to Eventzilla

**Save the Date** (box)
Event far in advance with date, presenter, title

Recommendations: 
Display condensed version of event that links to larger, more detailed version
Use a grid format to display info
Provide info for paying by mail on page rather than just event flyer

**Comment by wesruv** [comment]
This looks great!

I think that these two parts of the "Event List" are actually just one thing, since it doesn't seem to be a consistent part of events:
* Description of event
* Level of knowledge needed

However I really like the idea of "Level of knowledge" needed, we could suggest that and ask if that comes up a lot.

A nit-pick, I wouldn't quite call the two things marked as "Subheader" subheaders. In my mind subheaders are always single line and have the same treatment all the way through (either entire thing is a link, or nothing is). I'd just call them 'content chunks'.

They don't really tie to any other page, they're not really structured content, it's just the stuff they want to say at the top of this piece. Which means they'll need a way to make custom little chunks of copy or information on pages.
