### ISSUE TITLE
Content Inventory - Bookstore

### ISSUE THREAD

**Issue by wesruv** [wesruv/jungcentralohio.org#8]
Parent Issue: https://github.com/wesruv/jungcentralohio.org/issues/3

http://www.jungcentralohio.org/bookstore.html

Information we're trying to collect for the page above and it's sub-pages:
- [ ] How the pages/section fit into the site-tree/navigation
- [ ] Identify chunks of content that make up the page (e.g. the page is an 'event', but also has listings of upcoming events OR the page is the "about us page" but also has a listing of seminars, a summary of the lending library, and it lists the board members)
- [ ] Identify any 'special' functionality or behaviors. This includes search, listings of content, animating/interactive elements, etc.
- [ ] *Extra credit*, if you have any recommendations (e.g. this page might be better with a picture of X, or this piece of content could use a map, this page could be combined with another, etc)

**Comment by starbuck28** [comment]
# **Bookstore**

A major page linked to from home page navigation

Content areas include:

**Main Header** (text only)

**Library Catalog**

- Subheader (text only)
- Image- when clicked links to catalog in same window(Google doc)
- Instructions on how to use catalog

_Catalog_(Google Doc) contains list of library items
Library Item:

- Author
- Title
- Type of Item (book, DVD, etc)
- Publisher
- Publish Date
- Status
- Category
- Keywords

**Library**

- Subheader (text only)
- Image of library when clicked links to larger photo on new page
- Attribution of photo
- Link to larger picture on new page

**Bookstore**

- Subheader (text only)
- Image of bookstore when clicked links to larger photo on new page
- Attribution of photo
- Link to larger picture on new page


Description of discounts for members

Library/bookstore hours & contact info (phone number)

_Recommendations:_ 
-Transition catalog from Google Doc to a database/list within the JACO site
-Allow navigation from catalog to other pages on site (unable to navigate back intuitively from Google Doc)
-Provide more description of bookstore and library
-Instead of linking photos to new page- either do not link or provide lightbox photo

**Comment by wesruv** [comment]
Great work, love the recommendations!

I would identify Library and Bookstore as a single type of content that was used twice, it's a photo with title, image and attribution and optionally some text underneath. However I'd recommend to them that we do a bit more with those bits of content, it's unclear what their purpose is right now, and I think it's to get people to come visit them. Something we'll probably want to ask when we build this content (or the newer version of it).
